export const ADD_POPULAR_FILMS = "ADD_POPULAR_FILMS";
export const ADD_TOPRATED_FILMS = "ADD_TOPRATED_FILMS";
export const ADD_UPCOMING_FILMS = "ADD_UPCOMING_FILMS";
export const ADD_DESCRIPTION_FILM = "ADD_DESCRIPTION_FILM";
export const BROADCAST_ID = "BROADCAST_ID";